### ISSUE TITLE
Switch to MyST-Parser from recommonmark

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/sphinxcontrib-opendataservices#24]
recommonmark requires RST in your Markdown, or the use of the custom `markdown` directive from this repo; MyST Parser instead just parses the content of `note`, `csv-table`, etc. directives as Markdown, which is what you want.

recommonmark sometimes requires the custom `AutoStructifyLowPriority`; MyST-Parser doesn't interfere with translations.

For translations to work, a fork of recommonmark needs to be used. MyST-Parser just works.

recommonmark is basically unmaintained ([old PRs](https://github.com/readthedocs/recommonmark/pulls/jpmckinney) to fix translations, etc.). MyST-Parser is very responsive.

**Comment by jpmckinney** [comment]
recommonmark will be sunset in about a month: https://github.com/readthedocs/recommonmark/issues/221

**Comment by robredpath** [comment]
Thanks for this @jpmckinney - we'll take a look!

**Comment by robredpath** [comment]
We did this
