### ISSUE TITLE
Markdown in admonitions

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/sphinxcontrib-opendataservices#3]

**Comment by Bjwebb** [comment]
Instead of creating a new "example in markdown dirctive", I've created a `markdown` directive that can be embedded in a number of places, including admonitions. See https://sphinxcontrib-opendataservices.readthedocs.io/en/latest/#directive-markdown for an example. @timgdavies Does this do what you need?

**Comment by timgdavies** [comment]
This is great Ben :) Yes - this looks just the job.

**Comment by Bjwebb** [comment]
Docs are now at https://sphinxcontrib-opendataservices.readthedocs.io/en/latest/misc/#directive-markdown

**Comment by duncandewhurst** [comment]
I'm trying to use this directive in OC for Infrastructure on [this branch](https://github.com/open-contracting/infrastructure/tree/implementation-guidance), but the markdown isn't rendering.

In [assess-against-ids.md](https://github.com/open-contracting/infrastructure/blob/implementation-guidance/docs/guidance/assess-against-ids.md) I have the following:

```
```eval_rst
.. admonition:: Tip
    :class: Tip

    .. markdown::

    You can use the [OCDS Data Review Tool](http://standard.open-contracting.org/review/) to check that whether your data is published in OCDS format.
```
But the markdown hyperlink doesn't render:

![image](https://user-images.githubusercontent.com/19265814/49816100-14f62500-fd65-11e8-884f-89cda5e30327.png)

The latest commit in this repo is specified in [requirements.txt](https://github.com/open-contracting/infrastructure/blob/implementation-guidance/requirements.txt) and `conf.py` has `sphinxcontrib.opendataservices` in the `extensions` array per the installation instructions.

@robredpath could someone take a quick look at where I'm going wrong?

**Comment by duncandewhurst** [comment]
nevermind, I just needed to indent the text
