### ISSUE TITLE
Docs broken?

### ISSUE THREAD

**Issue by ghost** [OpenDataServices/sphinxcontrib-opendataservices#33]
https://sphinxcontrib-opendataservices.readthedocs.io/en/latest/jsoninclude/ looks wrong

**Comment by Bjwebb** [comment]
I think https://github.com/OpenDataServices/sphinxcontrib-opendataservices/pull/31 fixes this, but there's some more work to do before it's ready.

**Comment by jpmckinney** [comment]
Can be closed
