### ISSUE TITLE
Add a directive to render the description of a code in a blockquote

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/sphinxcontrib-opendataservices#42]
Similar to [JSON Include Quoted](https://sphinxcontrib-opendataservices.readthedocs.io/en/latest/jsoninclude/#json-include-quoted), it would be helpful if we could quote the description of codes from codelist csv files. That way, we won't need to worry about keeping the documentation in sync with any updates to the codelists.

For example, something like

````
```{codeinclude-quote} ../../codelists/open/organisationRole.csv
:code: networkProvider
```
````

Would render the description of the 'networkProvider' code from the [organisationRole codelist](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/0.1-dev/codelists/open/organisationRole.csv) as a blockquote:

> An organisation that operates the active network infrastructure, i.e. the electrical elements, such as optical transceivers, switches and routers. In open business models, network providers provide wholesale access to service providers such as retail internet service providers. Network providers can own or lease the active network infrastructure.

cc @lgs85

**Comment by jpmckinney** [comment]
You can use https://sphinxcontrib-opencontracting.readthedocs.io/en/latest/#code-description

You also didn't need jsoninclude-quote as https://sphinxcontrib-opencontracting.readthedocs.io/en/latest/#field-description already existed.

**Comment by duncandewhurst** [comment]
Awesome! I wasn't aware of these directives.
