### ISSUE TITLE
jsonschema: Relative links to anchors

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/sphinxcontrib-opendataservices#43]
The `jsonschema` directive use the `id` attribute to create an HTML anchor for each property in the schema tables it generates, e.g. https://open-fibre-data-standard.readthedocs.io/en/latest/reference/schema.html#network-schema.json,,nodes

How can I create relative links to these anchors?

If I add a link to the anchor in the [source markdown file](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/0.1/docs/reference/schema.md), like `[nodes](#network-schema.json,,nodes)`, and run `sphinx-build` with the `-nW` flag set (as usual), then I get the following error:

```
'myst' reference target not found: #network-schema.json,,nodes
```

If I run sphinx-build without the `-nW` flag, then it builds successfully but reports warnings and doesn't create the links.

An alternative option would be to use absolute links, like the one in the first paragraph, but it would be nice to have links that work on dev branches.

**Comment by jpmckinney** [comment]
I'm pretty sure the jsonschema directive needs to be setting `anchorname` (right now it sets it to `''`).

**Comment by jpmckinney** [comment]
Oh, actually, that's what the `addtargets` option is for: https://github.com/OpenDataServices/sphinxcontrib-opendataservices-jsonschema/pull/32

Edit: Links like `network-schema.json,,nodes` (no `#`) will then work.

**Comment by duncandewhurst** [comment]
Nice! Thanks for flagging.
